### ISSUE TITLE
Crafttweaker Todo pt1

### ISSUE THREAD

**Issue by RedRaspberry** [RedRaspberry/explorationtech#1]
- [ ] Ticon smeltery controller recipe that requires hardened glass and a metal plate
- [ ] Bugfix crushing table to properly use oredict
- [ ] Crushing table can crush all ores and create all plates
- [ ] Move railcraft recipes outside of the rolling machine
- [ ] Move various metalworking recipes to the rolling machine
- [ ] Remove the railcraft wire coil recipes and replace with equivalents from IE
- [ ] Unify the thermal and immersive bitumen thru oredict and recipes
- [ ] Salis Mundas should be made from an actual pestle&mortar
- [ ] Wire recipes
- [ ] Immersive mixer recipe to make pyrotheum, cryotheum, and etc.
- [ ] Recipes for Modular machinery cases and parts
- [ ] Distillation tower byproducts fix
- [ ] Immersive Intelligence circuit production as the ONLY method to get circuitbasic/advanced/elite, at least until around signalum level
 - [ ] Signalum and above machine cases and/or machines require circuits
- [ ] PSI items from precision assembler
