### ISSUE TITLE
Magic mod todo

### ISSUE THREAD

**Issue by RedRaspberry** [RedRaspberry/explorationtech#5]
- [ ] Thaumcraft infusion recipes for enchanted books not covered by the enchanting w/ thaumcraft mod
     - [ ] If possible add page to thaumcraft showing custom enchanting recipes?
- [ ] Thaumcraft infusion recipes for Electroblob's Wiz books
- [ ] Add page to Lexica Botania showing custom botania recipes
